### ISSUE TITLE
Separate ViewController into multiple files

### ISSUE THREAD

**Issue by jpsim** [realm/RealmTasks#112]
After #102, ViewController.swift is close to 800 lines 😱. There's a lot we can do to refactor this:
1. Encapsulate navigation logic & animations into the ContainerViewController
2. Move ContainerViewController to its own file (ok, slightly unrelated to ViewController.swift)
3. Encapsulate UITableView's KVO'd `contentView` into its own class or file (or replace this approach with a nicer one)
4. Look into encapsulating basically every `MARK` section into a separate file. This won't be possible for all of them, but should be possible for several.

**Comment by TimOliver** [comment]
`ViewController.swift` is a much more reasonable 350 LOC now. I think this issue is resolved. Good work @icanzilb! :)
