### ISSUE TITLE
Support self signed certificates

### ISSUE THREAD

**Issue by radu-tutueanu** [realm/RealmTasks#218]
If we want to use SSL in the demo, the app should support working with a self signed certificate.

Right now we get `2016-09-16 21:02:10.019 RealmTasks[2078:33845] Sync: Connection[1]: SSL handshake failed: Unknown SecureTransport error (-9807) (securetransport:-9807)`.

The Common Name of the certificate can be changed in line 31 of `start-object-server.command`

**Comment by stel** [comment]
Does "Support self signed certificates" mean disable SSL validation in this case?

If yes, this could be done by
```Swift
SyncManager.sharedManager().disableSSLValidation = true
```
when `realms://` is used.

In other case it's required to install the certificate or CA on the device in order for the device to trust it then only device trusts the SSL connection.

**Comment by radu-tutueanu** [comment]
Yes, that was correct. But we decided not to use SSL for the demo, so we can close it.
