### ISSUE TITLE
Switch to list text label not appearing properly on iOS 10

### ISSUE THREAD

**Issue by bigfish24** [realm/RealmTasks#255]
![simulator screen shot sep 25 2016 1 11 07 pm](https://cloud.githubusercontent.com/assets/1036685/18817944/b46cacf0-8321-11e6-84b3-b7575d47987b.png)

Using: https://github.com/realm/RealmTasks/commit/c2d0ced682b43b7117eec2c141268a673108599c

Appears like this on iOS simulator and on iPad Mini device in testing.

**Comment by jpsim** [comment]
Fixed in #295.
