### ISSUE TITLE
The RealmTasks for macOS app is not sandboxed

### ISSUE THREAD

**Issue by radu-tutueanu** [realm/RealmTasks#301]
Sandboxing is broken in the app we build and deliver  as part of the bundle.
@stel @TimOliver

**Comment by TimOliver** [comment]
Broken how? The sandboxing entitlement is enabled in the project already, but do we need to change any settings for it?

**Comment by stel** [comment]
@TimOliver yeah, the way Xcode works with signing was change in v8, I'm able to properly sandbox the app locally but not on CI, will investigate this.
