### ISSUE TITLE
Sync demo app from OS X bundle crashed on first login

### ISSUE THREAD

**Issue by austinzheng** [realm/RealmTasks#302]
I downloaded the OS X bundle, started the server, and opened the prebuilt copy of RealmTasks. Then I made a new account and pressed the log in button.

The app crashed with the following error:

```
Application Specific Information:
terminating with uncaught exception of type realm::RealmFileException: Unable to open a realm at path '/Users/austinzheng/Library/Application Support/io.realm.realmtasks.macos/realm-object-server/io.realm.object-server-metadata/sync_metadata.realm.management': make_dir() failed: No such file or directory.
```

This is really weird, because:
* The base URL (`/Users/austinzheng/Library/Application Support/io.realm.realmtasks.macos`) is provided by one of our APIs in `RLMUtil.mm` and itself is based on a well-known directory provided by the OS.
* All the intermediate directories should be created by the `NSFileManager` APIs.
* On the subsequent launch the directories were created properly and the app worked fine.

This is a bad user experience and I want to look into this issue more carefully.

**Comment by stel** [comment]
@austinzheng did you launch an app before starting the server? Currently there is a workaround in `.start-object-server.command` that removes this files:
```sh
if [ ! -f "$package/object-server/installed" ]; then
    echo "Deleting files from the previous version"
    rm -rf ~/Library/Containers/io.realm.{RealmTasks,realmbrowser,realmtasks.macos}
    ...
```

This should be removed after #205 is implemented.
