### ISSUE TITLE
Use of undeclared type 'User'

### ISSUE THREAD

**Issue by Coderii** [realm/RealmTasks#303]
when i run the project, it has 3 errors, Xcode log is “Use of undeclared type 'User'”,what can i do?

**Comment by TimOliver** [comment]
Hi @Coderii! 

`User` is a new type of object in the Realm Mobile Platform. If your Xcode build isn't picking it up, then it sounds like the latest version of `RealmSwift` wasn't installed properly.

Where did you get your copy of the project from? Did you clone it, or open it from our website bundle? The website version should have all dependencies pre-added, but downloading a copy from here will require CocoaPods.

Thanks!

**Comment by Coderii** [comment]
I fork your project, clone it with GitHub Desktop, then I use 'Pod install' to update your project so that i have all dependencies pre-added, but it also has the same error.（sorry my English is poor）[http://oeaoab0d4.bkt.clouddn.com/1.png](url)

**Comment by Coderii** [comment]
I fork your project, clone it with GitHub Desktop, then I use 'Pod install' to update your project so that i have all dependencies pre-added, but it also has the same error.（sorry my English is poor）
<img width="566" alt="1" src="https://cloud.githubusercontent.com/assets/16534022/18978631/36bc6488-86f7-11e6-8a4a-b6e1f4494968.png">

**Comment by Coderii** [comment]
<img width="645" alt="2" src="https://cloud.githubusercontent.com/assets/16534022/18978664/71e83f00-86f7-11e6-918d-318bdcff4527.png">

**Comment by stel** [comment]
@Coderii please try to run `pod update`. It looks like you have outdated local specs repo and also means that we need to specify `Realm` version in `Podfile` explicitly :)

**Comment by Coderii** [comment]
thank you！
