### ISSUE TITLE
[iOS] Ip address is empty if the computer has no external connection 

### ISSUE THREAD

**Issue by radu-tutueanu** [realm/RealmTasks#323]
If you are not connected to the internet, the ip address would be empty and the url becomes `realm://:9080/~/realmtasks` - which causes the app to crash with a BadServerUrl exception.
i would have expected the url to be 127.0.0.1 in this case.
@TimOliver

**Comment by jpsim** [comment]
We should fall back on `127.0.0.1`. Should be super easy to adapt the build phase to do so.
