### ISSUE TITLE
Where is encryption key for macOS local RealmDB?

### ISSUE THREAD

**Issue by kdawgwilk** [realm/RealmTasks#327]
When experimenting with the macOS version and realm mobile sync I wanted to open the macOS app local `.realm` db file and it asked for an encryption key.  I searched through the repo and couldn't seem to find a default key used anywhere.

**Comment by stel** [comment]
@kdawgwilk opening sync'd realm files locally are not supported currently.

**Comment by jpsim** [comment]
Filed https://github.com/realm/realm-core/issues/2276 to track adding support for that.

Closing since this is unrelated to RealmTasks.
