### ISSUE TITLE
[Xamarin] RealmTasks should allow install alongside others

### ISSUE THREAD

**Issue by AndyDentFree** [realm/RealmTasks#363]
The Xamarin versions for iOS and Android should have a unique signature to allow installation alongside the existing apps.

I suggest we change the final s to x ie `io.realm.realmtaskx`

**Comment by nirinchev** [comment]
I was thinking about `io.realm.realmtasx`, but @fealebenpae hated it 😿 We could also spell it out completely - `io.realm.tasks-xamarin`.

**Comment by jpsim** [comment]
please don't butcher the app name in the id for no reason. We use `io.realm.realmtasks.ios` and `io.realm.realmtasks.macos` so far, might as well use `io.realm.realmtasks.xamarin`.

**Comment by nirinchev** [comment]
io.realm.realmtasks.xamarin it is.
